import { type Metadata } from "next";
import { Fira_Code } from "next/font/google";

import "@/assets/css/globals.css";
import Providers from "@/components/providers";
import { cn } from "@/lib/utils";

const firaCode = Fira_Code({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={cn("antialiased", firaCode.className)}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
